[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^6
    h2zero/NimBLE-Arduino
    https://github.com/marcogallotta/PrayerTimes.git
    olikraus/U8g2

build_unflags =
  -std=gnu++11

build_flags =
    -Isrc
    -std=gnu++17

board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
