[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^6
    h2zero/NimBLE-Arduino
    https://github.com/marcogallotta/PrayerTimes.git
    olikraus/U8g2

build_unflags =
  -std=gnu++11

build_flags =
    -Isrc
    -std=gnu++17

board_build.filesystem = littlefs
board_build.partitions = no_ota.csv

[env:esp32s3-debug]
extends = env:esp32s3
build_flags =
    ${env:esp32s3.build_flags}
    -DPQUEUE_TEST_DEBUG=1

[env:esp32s3-history-test]
extends = env:esp32s3
build_flags =
    ${env:esp32s3.build_flags}
    -DSWITCHBOT_HISTORY_TEST_DEBUG=1
test_build_src = yes
build_src_filter =
    +<*>
    -<main.cpp>
